[Project]
cubic_version = 2026.02.102-release~202602080448~ubuntu25.10.1
first_version = 2026.02.102-release~202602080448~ubuntu25.10.1
create_date = 2026-04-14 18:21
modify_date = 2026-04-14 18:21
directory = /home/giosu-francesco-marraffa/Scrivania/SunshineOS

[Original]
iso_file_name = sunshineos-1.0-desktop.iso
iso_directory = /home/giosu-francesco-marraffa/Scrivania/SunshineOS
iso_volume_id = SunshineOS
iso_release_name = Leonardus
iso_disk_name = SunshineOS "Leonardus"

[Custom]
iso_version_number = 1.0
iso_file_name = sunshineos-1.0-desktop-1.0.iso
iso_directory = /home/giosu-francesco-marraffa/Scrivania/SunshineOS
iso_volume_id = SunshineOS 1.0
iso_release_name = Leonardus
iso_disk_name = SunshineOS 1.0 "Leonardus"

[Layout]
casper_directory = casper
squashfs_directory = casper
squashfs_file_name = 
manifest_file_name = filesystem.manifest
minimal_remove_file_name = 
standard_remove_file_name = 
size_file_name = filesystem.size
minimal_squashfs_file_name = minimal.squashfs
minimal_manifest_file_name = minimal.manifest
minimal_size_file_name = minimal.size
standard_squashfs_file_name = minimal.standard.squashfs
standard_manifest_file_name = 
standard_size_file_name = minimal.standard.size
installer_sources_file_name = install-sources.yaml
installer_squashfs_file_name = minimal.standard.live.squashfs
installer_manifest_file_name = minimal.standard.live.manifest
installer_size_file_name = minimal.standard.live.size
installer_generic_squashfs_file_name = 
installer_generic_manifest_file_name = 
installer_generic_size_file_name = 

[Status]
is_success_analyze = True
is_success_copy = True
is_success_extract = True
iso_template = 789C8D51CD8E832010BEFB14DCBCEC54C59FAA0FB25732C06848500CD0266DD3775F6DDDA69B6CB27B80C03730DFCFC0274B6F67674F1309A3EF690230FA93E43049CF00CC1CC99FD1F6D629B462087D1EA0A8437F25EFC4FA66891F8FE3B8C43EBD49E7A230138E24B4F1A4A2F3977BB6A08F261A37437130D3B8712CDEC5B56CCE0453D02E8045493681D753A12E56A035E3CCDC30BC17D66BA0C88A666DB30A80C17945B031A3B494002E0BCD5ABC3E30CE787B2C39AAA2188656F3A29058C93CC75C7525AD4BFE6E544391F3BAD6FD3F8CF1DDD8939C9EF402C3964B02263CB27A82F1B210438EB9CE49522DBBB2ACAAF6A8F2A6958D3CF2A6EBD43101C5D26C633D288C68DDD65CEE50B64D283365DBC0A232B2AB1813DDAE607640D3C93E02491E3B58871A82B912AB76C4CC83833DAF7DDE2F3C81EF8E8036EE7D88A56F19FD70F99C0AEFD1DA35A93F046C8936C917BD69D854
iso_checksum = 
iso_checksum_file_name = 

[Options]
update_os_release = True
has_minimal_install = False
boot_configurations = 
compression = gzip

